---
- ansible.builtin.import_playbook: update.yml
- name : Schemas and Templates
  gather_facts: false
  hosts: all
  tasks:

    - name: Add a new template to a schema
      cisco.mso.mso_schema_template:
        schema: "{{ item.name }}"
        state: "{{ item.status if item.status is defined else omit }}"
        template: "{{ item.template }}"
        tenant: "{{ item.tenant }}"
        template_type: "{{ item.template_type }}"
      loop: "{{ schema }}"
      when: schema is defined

    - name: Add a site to a schema
      cisco.mso.mso_schema_site:
        schema: "{{ item.schema_name }}"
        template: "{{ item.template_name }}"
        site: "{{ item.site_name }}"
        state: "{{ item.status if item.status is defined else omit }}"
      loop: "{{ template_site_association }}"
      when: template_site_association is defined

